Temp disable search tests

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -140,24 +140,24 @@ steps:
       echo "Pool `tank` not found"
       exit 1
     fi
-  ### Create snapshot from default for search and import tests
-  - |
-    SNAPSHOT_NAME="tank/default@ci-default-$RUNID"
-    CLONE_NAME="tank/ci-default-clone-$RUNID"
-    zfs snapshot -r $SNAPSHOT_NAME
-    zfs clone $SNAPSHOT_NAME $CLONE_NAME
-    zfs set mountpoint=/tmp/default $CLONE_NAME
+  # ### Create snapshot from default for search and import tests
+  # - |
+  #   SNAPSHOT_NAME="tank/default@ci-default-$RUNID"
+  #   CLONE_NAME="tank/ci-default-clone-$RUNID"
+  #   zfs snapshot -r $SNAPSHOT_NAME
+  #   zfs clone $SNAPSHOT_NAME $CLONE_NAME
+  #   zfs set mountpoint=/tmp/default $CLONE_NAME
 
-  ### Create snapshot from goldet for search tests 
-  - |
-    SNAPSHOT_NAME="tank/golden@ci-$RUNID"
-    CLONE_NAME="tank/ci-golden-clone-$RUNID"
-    zfs snapshot -r $SNAPSHOT_NAME
-    zfs clone $SNAPSHOT_NAME $CLONE_NAME
-    zfs set mountpoint=/tmp/golden $CLONE_NAME
+  # ### Create snapshot from goldet for search tests 
+  # - |
+  #   SNAPSHOT_NAME="tank/golden@ci-$RUNID"
+  #   CLONE_NAME="tank/ci-golden-clone-$RUNID"
+  #   zfs snapshot -r $SNAPSHOT_NAME
+  #   zfs clone $SNAPSHOT_NAME $CLONE_NAME
+  #   zfs set mountpoint=/tmp/golden $CLONE_NAME
     
-  # Verify mount
-  - zfs list -o name,mounted,mountpoint | grep ci- || true
+  # # Verify mount
+  # - zfs list -o name,mounted,mountpoint | grep ci- || true
 
   ## GCP auth
   - printf "%s" "$DRONE_CI_GCP_SA" > /tmp/key.json
@@ -181,16 +181,16 @@ steps:
   - sleep 120
   - docker compose down -v
   
-  ## Cleanup ZFS clone
-  - |
-    if command -v zfs >/dev/null 2>&1 && zfs list | grep "tank/ci-"; then
-      echo "Cleaning up ZFS clones..."
-      for clone in $(zfs list -H -o name | grep "tank/ci-clone"); do
-        echo "Destroying clone: $clone"
-        zfs destroy -r $clone || true
-      done
-    fi
-  ## ----------------------------------------------------
+  # ## Cleanup ZFS clone
+  # - |
+  #   if command -v zfs >/dev/null 2>&1 && zfs list | grep "tank/ci-"; then
+  #     echo "Cleaning up ZFS clones..."
+  #     for clone in $(zfs list -H -o name | grep "tank/ci-clone"); do
+  #       echo "Destroying clone: $clone"
+  #       zfs destroy -r $clone || true
+  #     done
+  #   fi
+  # ## ----------------------------------------------------
 
   # ## Run infra for search tests
   # - ./runner.sh bootstrap -f ci_search_suite.yaml -f docker-compose.override.yml
